extends Node

signal score_changed(new_score)
signal coins_changed(new_coins)
signal game_over
signal keys_changed(new_keys)
signal milestone_reached(tier: int, score_value: int)
signal new_best_reached(score: int)
signal tier_unlocked(tier: int)
signal ad_reward_granted(amount: int)

enum GameState {
	IDLE,
	PLAYING,
	GAME_OVER
}

enum PowerupType {
	FREEZE,
	SHAKE,
	PLUCK,
	CURE,
	PURGE,
	BOMB,
	REFRESH,
	RIPPLE
}

const TIER_THRESHOLDS = [
	0,       # tier 1
	0,       # tier 2
	0,       # tier 3
	100,       # tier 4
	200,       # tier 5
	1000,    # tier 6
	2000,    # tier 7
	5000,    # tier 8
	9000,   # tier 9
	11000,   # tier 10
	20000,   # tier 11
	34000,   # tier 12
	55000,   # tier 13
	75000,   # tier 14
	105000    # tier 15
]

const POWERUP_COSTS = {
	PowerupType.FREEZE: 0,
	PowerupType.SHAKE: 25,
	PowerupType.PLUCK: 25,
	PowerupType.CURE: 40,
	PowerupType.PURGE: 80,
	PowerupType.BOMB: 40,
	PowerupType.REFRESH: 100,
	PowerupType.RIPPLE: 100
}

const SCORE_TO_COIN_RATIO = 100

# --------------------------------------------------
# CORE DATA
# --------------------------------------------------

var state: GameState = GameState.IDLE

var score: int = 0
var high_score: int = 0

# Permanent saved coins
var coins: int = 0

# Coins earned THIS RUN only
var run_coins: int = 0
var last_run_earned_coins: int = 0
# Total generated by score THIS RUN
# Prevents regeneration bugs
var generated_run_coins: int = 0

var keys: int = 0
var unlocked_max_tier: int = 3

var run_rewarded := false
var milestones_hit_this_run: Array = []
var new_best_announced_this_run := false

var _save_pending := false
# --------------------------------------------------
# FREE TRIALS
# --------------------------------------------------

var free_trials: Dictionary = {
	PowerupType.FREEZE: true,
	PowerupType.SHAKE: true,
	PowerupType.PLUCK: true,
	PowerupType.CURE: true,
	PowerupType.PURGE: true,
	PowerupType.BOMB: true,
	PowerupType.REFRESH: true,
	PowerupType.RIPPLE: true
}

# --------------------------------------------------
# READY
# --------------------------------------------------

func _ready():
	load_save()
	
# --------------------------------------------------
# GAME FLOW
# --------------------------------------------------

func start_game():
	score = 0
	run_coins = 0
	generated_run_coins = 0
	run_rewarded = false
	milestones_hit_this_run = []
	new_best_announced_this_run = false

	state = GameState.PLAYING
	emit_signal(
		"score_changed",
		score
	)
	emit_signal(
		"coins_changed",
		get_total_coins()
	)

func trigger_game_over():

	if state == GameState.GAME_OVER:
		return

	state = GameState.GAME_OVER

	end_run()

	emit_signal("game_over")

func end_run():

	if run_rewarded:
		return 0

	run_rewarded = true

	# Bank temporary run coins
	coins += run_coins

	var earned = run_coins
	last_run_earned_coins = earned
	run_coins = 0

	print(
		"Run ended. Earned coins: ",
		earned
	)

	emit_signal(
		"coins_changed",
		get_total_coins()
	)

	request_save()

	return earned

# --------------------------------------------------
# SCORE / COINS
# --------------------------------------------------

func add_score(value: int):

	score += value

	# New best score — only ever emit once per run, the first time it happens
	if score > high_score:
		high_score = score
		if not new_best_announced_this_run:
			new_best_announced_this_run = true
			emit_signal("new_best_reached", score)

	# Score milestone check — did we just cross a tier threshold?
	for i in range(TIER_THRESHOLDS.size()):
		var threshold = TIER_THRESHOLDS[i]
		if threshold > 0 and score >= threshold and not (i in milestones_hit_this_run):
			milestones_hit_this_run.append(i)
			emit_signal("milestone_reached", i + 1, threshold)

	# Calculate how many coins SHOULD exist

	# Calculate how many coins SHOULD exist
	var should_have = int(score / SCORE_TO_COIN_RATIO)

	# Generate only missing coins
	var to_generate = (
		should_have
		- generated_run_coins
	)

	if to_generate > 0:

		run_coins += to_generate

		generated_run_coins += to_generate

		emit_signal(
			"coins_changed",
			get_total_coins()
		)

	emit_signal(
		"score_changed",
		score
	)

func get_total_coins() -> int:
	return coins + run_coins

func get_run_coin_preview() -> int:
	return run_coins

# --------------------------------------------------
# POWERUPS
# --------------------------------------------------

func can_use_powerup(
	type: PowerupType
) -> bool:
	
	if type == PowerupType.FREEZE:
		return false
		
	if free_trials[type]:
		return true

	return get_total_coins() >= POWERUP_COSTS[type]

func use_powerup(
	type: PowerupType
) -> bool:

	# ---------------- FREE TRIAL ----------------

	if free_trials[type]:

		free_trials[type] = false

		request_save()

		return true

	# ---------------- NORMAL PURCHASE ----------------

	var cost = POWERUP_COSTS[type]

	if get_total_coins() < cost:
		return false

	# Spend RUN coins first
	if run_coins >= cost:

		run_coins -= cost

	else:

		var remaining = (
			cost - run_coins
		)

		run_coins = 0

		coins -= remaining

	emit_signal(
		"coins_changed",
		get_total_coins()
	)

	request_save()

	return true

func add_coins_from_ad(type: PowerupType):
	var amount = POWERUP_COSTS[type]
	coins += amount
	emit_signal("coins_changed", get_total_coins())
	
	emit_signal("ad_reward_granted", amount)
	request_save()

# --------------------------------------------------
# KEYS
# --------------------------------------------------

func add_key():

	keys += 1

	emit_signal(
		"keys_changed",
		keys
	)

	request_save()

func add_keys(amount: int):

	keys += amount

	emit_signal(
		"keys_changed",
		keys
	)

	request_save()

# --------------------------------------------------
# TIERS
# --------------------------------------------------

func unlock_tier(tier: int):

	if tier > unlocked_max_tier:

		unlocked_max_tier = tier
		emit_signal("tier_unlocked", tier)

		request_save()

# --------------------------------------------------
# SAVE / LOAD
# --------------------------------------------------
func request_save():
	if _save_pending:
		return
	_save_pending = true
	call_deferred("_flush_save")

func _flush_save():
	_save_pending = false
	save_game()
	
func save_game():
	
	var data = {

		"high_score": high_score,

		"coins": coins,

		"keys": keys,

		"unlocked_max_tier":
			unlocked_max_tier,
			
		"current_skin": current_skin,
		
		"unlocked_skins": unlocked_skins,

		"free_trials": {

			"0":
				free_trials[
					PowerupType.FREEZE
				],

			"1":
				free_trials[
					PowerupType.SHAKE
				],

			"2":
				free_trials[
					PowerupType.PLUCK
				],

			"3":
				free_trials[
					PowerupType.CURE
				],

			"4":
				free_trials[
					PowerupType.PURGE
				],

			"5":
				free_trials[
					PowerupType.BOMB
				],

			"6":
				free_trials[
					PowerupType.REFRESH
				],

			"7":
				free_trials[
					PowerupType.RIPPLE
				]
		}
	}
	

	var file = FileAccess.open(
		"user://save.json",
		FileAccess.WRITE
	)

	file.store_string(
		JSON.stringify(data)
	)

	file.close()

func load_save():

	if not FileAccess.file_exists(
		"user://save.json"
	):
		return

	var file = FileAccess.open(
		"user://save.json",
		FileAccess.READ
	)

	var data = JSON.parse_string(
		file.get_as_text()
	)

	file.close()

	if not data:
		return

	high_score = data.get(
		"high_score",
		0
	)

	coins = data.get(
		"coins",
		0
	)

	keys = data.get(
		"keys",
		0
	)

	unlocked_max_tier = data.get(
		"unlocked_max_tier",
		3
	)
	
	current_skin = data.get("current_skin", 0)
	unlocked_skins = data.get("unlocked_skins", [true, false, false, false, false])
	
	var ft = data.get(
		"free_trials",
		{}
	)

	if ft:

		free_trials[
			PowerupType.FREEZE
		] = ft.get("0", true)

		free_trials[
			PowerupType.SHAKE
		] = ft.get("1", true)

		free_trials[
			PowerupType.PLUCK
		] = ft.get("2", true)

		free_trials[
			PowerupType.CURE
		] = ft.get("3", true)

		free_trials[
			PowerupType.PURGE
		] = ft.get("4", true)

		free_trials[
			PowerupType.BOMB
		] = ft.get("5", true)

		free_trials[
			PowerupType.REFRESH
		] = ft.get("6", true)

		free_trials[
			PowerupType.RIPPLE
		] = ft.get("7", true)

	emit_signal(
		"coins_changed",
		get_total_coins()
	)

	emit_signal(
		"keys_changed",
		keys
	)
func grant_powerup_from_ad(_type: PowerupType):
	# No coin transaction — just fires the powerup
	# Optionally track ad usage here later
	pass
	


signal skin_changed(skin_index)
var unlocked_skins: Array = [true, false, false, false, false]
var current_skin: int = 0

func select_skin(index: int):
	if not unlocked_skins[index]:
		return
	current_skin = index
	emit_signal("skin_changed", index)
	request_save()

func unlock_skin(index: int) -> bool:
	var cost = [0, 3, 5, 15, 30][index]
	if keys < cost:
		return false
	keys -= cost
	unlocked_skins[index] = true
	emit_signal("keys_changed", keys)
	request_save()
	return true

func get_current_max_tier() -> int:

	var max_tier := 1

	for i in range(TIER_THRESHOLDS.size()):

		if score >= TIER_THRESHOLDS[i]:
			max_tier = i + 1

	return max_tier
